# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
    push:
        branches:
            - "main"

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Manual Checkout
            - uses: actions/checkout@v4

            # Set up Node, and make sure it matches the version on your local machine
            - uses: actions/setup-node@v4
              with:
                  node-version: "20.11.1" 

            # Add Storybook build and deploy to GitHub Pages as a step in the workflow
            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  path: storybook-static
                  checkout: false